use crate::types::{ScanResult, Severity};

use super::Reporter;

pub struct MarkdownReporter;

impl Reporter for MarkdownReporter {
    fn name(&self) -> &str {
        "markdown"
    }

    fn render(&self, result: &ScanResult) -> String {
        let mut lines: Vec<String> = Vec::new();

        lines.push(format!("# Skill Scan Report: {}", result.skill_name));
        lines.push(String::new());
        lines.push(format!("- **Version**: {}", result.skill_version));
        lines.push(format!("- **Scanned At**: {}", result.scanned_at));
        lines.push(format!("- **Scanner Version**: {}", result.scanner_version));
        lines.push(format!("- **Duration**: {}ms", result.duration_ms));
        lines.push(format!("- **Decision**: {}", result.decision.as_str()));
        lines.push(String::new());

        lines.push("## Summary".to_string());
        lines.push(String::new());
        lines.push("| Severity | Count |".to_string());
        lines.push("|----------|-------|".to_string());
        lines.push(format!("| P0 (Blocker) | {} |", result.summary.p0));
        lines.push(format!("| P1 (Consent) | {} |", result.summary.p1));
        lines.push(format!("| P2 (Suggestion) | {} |", result.summary.p2));
        lines.push(String::new());

        if !result.findings.is_empty() {
            lines.push("## Findings".to_string());
            lines.push(String::new());

            let severities = [Severity::P0, Severity::P1, Severity::P2];
            let labels = ["P0", "P1", "P2"];

            for (sev, label) in severities.iter().zip(labels.iter()) {
                let findings: Vec<_> =
                    result.findings.iter().filter(|f| f.severity == *sev).collect();
                if findings.is_empty() {
                    continue;
                }
                lines.push(format!("### {} ({})", label, findings.len()));
                lines.push(String::new());
                for f in &findings {
                    lines.push(format!("#### {}", f.rule_id));
                    lines.push(format!("- **Message**: {}", f.message));
                    lines.push(format!(
                        "- **File**: {}",
                        f.file.as_deref().unwrap_or("")
                    ));
                    lines.push(format!("- **Category**: {}", f.category.as_str()));
                    if let Some(ref evidence) = f.evidence {
                        lines.push(format!("- **Evidence**: `{}`", evidence));
                    }
                    if let Some(ref rec) = f.recommendation {
                        lines.push(format!("- **Recommendation**: {}", rec));
                    }
                    lines.push(String::new());
                }
            }
        } else {
            lines.push("## Findings".to_string());
            lines.push(String::new());
            lines.push("No findings. Skill passed all checks.".to_string());
            lines.push(String::new());
        }

        lines.push("---".to_string());
        lines.push(format!(
            "*Report generated by skill-scanner v{}*",
            result.scanner_version
        ));

        lines.join("\n")
    }
}
