import { Reporter } from './types';
import { ScanResult, isBlocked } from '../types';

export class MarkdownReporter implements Reporter {
  name = 'markdown';

  render(result: ScanResult): string {
    const lines: string[] = [];
    lines.push(`# Skill Scan Report: ${result.skillName}`);
    lines.push('');
    lines.push(`- **Version**: ${result.skillVersion}`);
    lines.push(`- **Scanned At**: ${result.scannedAt}`);
    lines.push(`- **Scanner Version**: ${result.scannerVersion}`);
    lines.push(`- **Duration**: ${result.durationMs}ms`);
    lines.push(`- **Decision**: ${result.decision}`);
    lines.push('');

    lines.push('## Summary');
    lines.push('');
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    lines.push(`| P0 (Blocker) | ${result.summary.P0} |`);
    lines.push(`| P1 (Consent) | ${result.summary.P1} |`);
    lines.push(`| P2 (Suggestion) | ${result.summary.P2} |`);
    lines.push('');

    if (result.findings.length > 0) {
      lines.push('## Findings');
      lines.push('');

      const bySeverity = {
        P0: result.findings.filter((f) => f.severity === 'P0'),
        P1: result.findings.filter((f) => f.severity === 'P1'),
        P2: result.findings.filter((f) => f.severity === 'P2'),
      };

      for (const [severity, findings] of Object.entries(bySeverity)) {
        if (findings.length === 0) continue;
        lines.push(`### ${severity} (${findings.length})`);
        lines.push('');
        for (const f of findings) {
          lines.push(`#### ${f.ruleId}`);
          lines.push(`- **Message**: ${f.message}`);
          lines.push(`- **File**: ${f.file}`);
          lines.push(`- **Category**: ${f.category}`);
          if (f.evidence) lines.push(`- **Evidence**: \`${f.evidence}\``);
          if (f.recommendation) lines.push(`- **Recommendation**: ${f.recommendation}`);
          lines.push('');
        }
      }
    } else {
      lines.push('## Findings');
      lines.push('');
      lines.push('No findings. Skill passed all checks.');
      lines.push('');
    }

    lines.push('---');
    lines.push(`*Report generated by skill-scanner v${result.scannerVersion}*`);

    return lines.join('\n');
  }
}
